### ISSUE TITLE
Unable to parse ``await`` keyword in python 3.6

### ISSUE THREAD

**Issue by yushao2** [PyCQA/astroid#1004]
Not too sure if this is a bug

### Steps to reproduce

1. launch python interactive shell 
2.

``` python
Python 3.6.13 (default, Jun  1 2021, 00:41:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroid import extract_node
>>> code = '''def not_async():
    print(await 1) #@'''
>>> node = extract_node(code)
```

### Current behavior
```
Traceback (most recent call last):
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 172, in _data_build
    node, parser_module = _parse_string(data, type_comments=True)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 449, in _parse_string
    parsed = parser_module.parse(data + "\n", type_comments=type_comments)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/_ast.py", line 48, in parse
    return parse_func(string)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/typed_ast/ast3.py", line 62, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 2
    print(await 1) #@
                ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 426, in extract_node
    tree = parse(code, module_name=module_name)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 283, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 146, in string_build
    module = self._data_build(data, modname, path)
  File "/home/ys/Documents/workspace/pylint/venv3.6/lib/python3.6/site-packages/astroid/builder.py", line 180, in _data_build
    ) from exc
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 2)
```
### Expected behavior

Parsing to be successful to return a call node

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.5.6

**Comment by yushao2** [comment]
Closing this as I realised that python 3.6 will always throw an error for the example given
