### ISSUE TITLE
2.11.7 install error with python3.6

### ISSUE THREAD

**Issue by jsofri** [PyCQA/astroid#1713]
I suspect version 2.11.7 causes an error in `pip install pylint` when running with python3.6.
Last time I did it, version 2.11.6 was installed, successfully.
### Steps to reproduce
environment: centos7.9 with python3.6 (aarch64)
run: `pip3 install pylint`

### Current behavior
```
Collecting pylint
  Downloading https://files.pythonhosted.org/packages/03/09/7b710f4aab53e3ccc0d9596557bf020c5ad06312e54ec1b60402ec9d694f/pylint-2.13.9-py3-none-any.whl (438kB)
Collecting dill>=0.2 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl (86kB)
Collecting platformdirs>=2.2.0 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b1/78/dcfd84d3aabd46a9c77260fb47ea5d244806e4daef83aa6fe5d83adb182c/platformdirs-2.4.0-py3-none-any.whl
Collecting typing-extensions>=3.10.0; python_version < "3.10" (from pylint)
  Downloading https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Collecting isort<6,>=4.2.5 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b8/5b/f18e227df38b94b4ee30d2502fd531bebac23946a2497e5595067a561274/isort-5.10.1-py3-none-any.whl (103kB)
Collecting mccabe<0.8,>=0.6 (from pylint)
  Downloading https://files.pythonhosted.org/packages/27/1a/1f68f9ba0c207934b35b86a8ca3aad8395a3d6dd7921c0686e23853ff5a9/mccabe-0.7.0-py2.py3-none-any.whl
Collecting tomli>=1.1.0; python_version < "3.11" (from pylint)
  Downloading https://files.pythonhosted.org/packages/05/e4/74f9440db36734d7ba83c574c1e7024009ce849208a41f90e94a134dc6d1/tomli-1.2.3-py3-none-any.whl
Collecting astroid<=2.12.0-dev0,>=2.11.5 (from pylint)
  Downloading https://files.pythonhosted.org/packages/e4/3b/f1aa1bd41e8188b3a3605d71b699b73695fc7ac862cbed23ed9dee707251/astroid-2.11.7-py3-none-any.whl (251kB)
Requirement already satisfied: setuptools>=20.0 in /usr/lib/python3.6/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
Collecting wrapt<2,>=1.11 (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/11/eb/e06e77394d6cf09977d92bff310cb0392930c08a338f99af6066a5a98f92/wrapt-1.14.1.tar.gz (50kB)
Collecting typed-ast<2.0,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/07/d2/d55702e8deba2c80282fea0df53130790d8f398648be589750954c2dcce4/typed_ast-1.5.4.tar.gz (252kB)
Collecting lazy-object-proxy>=1.4.0 (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/75/93/3fc1cc28f71dd10b87a53b9d809602d7730e84cc4705a062def286232a9c/lazy-object-proxy-1.7.1.tar.gz (41kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kj2640cd/lazy-object-proxy/setup.py", line 146, in <module>
        distclass=BinaryDistribution,
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
        return self.resolve()
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-build-kj2640cd/lazy-object-proxy/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
```

### Expected behavior
no error. for reference, this is the output I got about a month ago, installing astroid version 2.11.6
```
Collecting pylint
  Downloading https://files.pythonhosted.org/packages/03/09/7b710f4aab53e3ccc0d9596557bf020c5ad06312e54ec1b60402ec9d694f/pylint-2.13.9-py3-none-any.whl (438kB)
Collecting isort<6,>=4.2.5 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b8/5b/f18e227df38b94b4ee30d2502fd531bebac23946a2497e5595067a561274/isort-5.10.1-py3-none-any.whl (103kB)
Collecting astroid<=2.12.0-dev0,>=2.11.5 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b6/38/1b2188bea6b5346ea2f97f063c99fdadb36707a7b3a95ff4fe73e242c33c/astroid-2.11.6-py3-none-any.whl (251kB)
Collecting platformdirs>=2.2.0 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b1/78/dcfd84d3aabd46a9c77260fb47ea5d244806e4daef83aa6fe5d83adb182c/platformdirs-2.4.0-py3-none-any.whl
Collecting dill>=0.2 (from pylint)
  Downloading https://files.pythonhosted.org/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl (86kB)
Collecting typing-extensions>=3.10.0; python_version < "3.10" (from pylint)
  Downloading https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Collecting tomli>=1.1.0; python_version < "3.11" (from pylint)
  Downloading https://files.pythonhosted.org/packages/05/e4/74f9440db36734d7ba83c574c1e7024009ce849208a41f90e94a134dc6d1/tomli-1.2.3-py3-none-any.whl
Collecting mccabe<0.8,>=0.6 (from pylint)
  Downloading https://files.pythonhosted.org/packages/27/1a/1f68f9ba0c207934b35b86a8ca3aad8395a3d6dd7921c0686e23853ff5a9/mccabe-0.7.0-py2.py3-none-any.whl
Collecting wrapt<2,>=1.11 (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/11/eb/e06e77394d6cf09977d92bff310cb039[2930](https://gitlab-master.nvidia.com/telemetry/Collectx/-/jobs/39452633#L2930)c08a338f99af6066a5a98f92/wrapt-1.14.1.tar.gz (50kB)
Collecting lazy-object-proxy>=1.4.0 (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/75/93/3fc1cc28f71dd10b87a53b9d809602d7730e84cc4705a062def286232a9c/lazy-object-proxy-1.7.1.tar.gz (41kB)
Requirement already satisfied: setuptools>=20.0 in /usr/lib/python3.6/site-packages (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
Collecting typed-ast<2.0,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<=2.12.0-dev0,>=2.11.5->pylint)
  Downloading https://files.pythonhosted.org/packages/07/d2/d55702e8deba2c80282fea0df53130790d8f398648be589750954c2dcce4/typed_ast-1.5.4.tar.gz (252kB)
Installing collected packages: cpplint, isort, wrapt, lazy-object-proxy, typing-extensions, typed-ast, astroid, platformdirs, dill, tomli, mccabe, pylint, pause, psutil
  Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Running setup.py install for lazy-object-proxy: started
    Running setup.py install for lazy-object-proxy: finished with status 'done'
  Running setup.py install for typed-ast: started
    Running setup.py install for typed-ast: finished with status 'done'
  Running setup.py install for pause: started
    Running setup.py install for pause: finished with status 'done'
  Running setup.py install for psutil: started
    Running setup.py install for psutil: finished with status 'done'
Successfully installed astroid-2.11.6  dill-0.3.4 isort-5.10.1 lazy-object-proxy-1.7.1 mccabe-0.7.0 platformdirs-2.4.0 pylint-2.13.9 tomli-1.2.3 typed-ast-1.5.4 typing-extensions-4.1.1 wrapt-1.14.1
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening an issue. Without going into a full on investigation, I think the dependency to ``setuptool_scm`` were loosely defined in pylint, (no upper bound ?) and the minimal python interpreter might not be set precisely in newer version of ``setuptool_scm``. A new release of ``setuptool_scm`` says it's compatible with 3.6 to pip, but it's in fact not. Could you try setting ``setuptools_scm`` to an older version ?

I don't think we're going to fix this release, we do not support python 3.6 anymore and the release process was a lot less automated at the time. Setting setuptool_scm is not a lot of work, but releasing a new 2.11.8 version is and it can't be done by an external contributors, it has to be us.

**Comment by jsofri** [comment]
> Thank you for opening an issue. Without going into a full on investigation, I think the dependency to `setuptool_scm` were loosely defined in astroid, (no upper bound ?) and the minimal python interpreter might not be set precisely in newer version of `setuptool_scm`. A new release of `setuptool_scm` says it's compatible with 3.6 to pip, but it's in fact not. Could you try setting `setuptools_scm` to an older version ?
> 
> I don't think we're going to fix this release, we do not support python 3.6 anymore and the release process was a lot less automated at the time. Setting setuptool_scm is not a lot of work, but releasing a new 2.11.8 version is and it can't be done by an external contributors, it has to be us.

@Pierre-Sassoulas I am not sure this is the reason since it works on x86

**Comment by Pierre-Sassoulas** [comment]
I don't know about ``x86`` but the content of ``/tmp/pip-build-kj2640cd/lazy-object-proxy/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5`` can't ever work on 3.6 because of ``from __future__ import annotations``, and it's part of ``setuptools_scm`` / ``lazy-object-proxy`` that's why I suggest to set a version compatible to python 3.6 for those two manually.
