### ISSUE TITLE
Inference crash in inferring value of `a % b`

### ISSUE THREAD

**Issue by tushar-deepsource** [PyCQA/astroid#1737]
```python
import astroid

code = """
def foo(x, y):
    return ("%" + str(x)) % y

foo("123", "f")
"""

tree = astroid.parse(code)
call_node = tree.body[1].value
print(list(call_node.infer()))
```

Output:

```text
Traceback (most recent call last):
  File "/Users/tusharsadhwani/asd.py", line 12, in <module>
    print(list(call_node.infer()))
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    yield from self._infer(context=context, **kwargs)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 264, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1748, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/decorators.py", line 126, in yes_if_nothing_inferred
    yield next(generator)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 530, in _filter_operation_errors
    for result in infer_callable(self, context):
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 879, in _infer_binop
    yield from _infer_binary_operation(lhs, rhs, self, context, _get_binop_flow)
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 828, in _infer_binary_operation
    results = list(method())
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 667, in _invoke_binop_inference
    return iter(_infer_old_style_string_formatting(instance, other, context))
  File "/Users/tusharsadhwani/venv3/lib/python3.10/site-packages/astroid/inference.py", line 650, in _infer_old_style_string_formatting
    return (nodes.const_factory(instance.value % values),)
ValueError: incomplete format
```

**Comment by jacobtylerwalls** [comment]
Could you provide the version you tested against?

**Comment by tushar-deepsource** [comment]
@jacobtylerwalls 2.12.2
