### ISSUE TITLE
Astroid 2.12.4 broken on PyPy 3.8 when `importlib.import_module` is used.

### ISSUE THREAD

**Issue by emcd** [PyCQA/astroid#1755]
EDIT: ~[Commit ddfba9c583287436f1c3498cb9f5fd919fb33ed0](https://github.com/PyCQA/astroid/commit/ddfba9c583287436f1c3498cb9f5fd919fb33ed0) is suspect.~ The actual suspect is further back in time.

### Steps to reproduce

1. Prepare an environment based on PyPy 7.3.9 (Python 3.8).
2. Install latest Pylint and Astroid in this environment.
3. Run Pylint against a Python source file, such as the following reproducer:
    ``` python
   from importlib import import_module
   package = import_module( 'os' )
    ```
4. Observe an error along the lines of what is described in the `Current Behavior` section below.

### Current behavior

```
Exception on node <ImportFrom l.1 at 0x7f57db63c448> in file '/home/me/src/python-lockup/astroid-bug.py'
Traceback (most recent call last):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/manager.py", line 249, in file_from_module_name
    value = self._mod_file_cache[(modname, contextfile)]
KeyError: ('_frozen_importlib', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/pylint/checkers/imports.py", line 798, in _get_imported_module
    return importnode.do_import_module(modname)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/_base_nodes.py", line 149, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 521, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/manager.py", line 208, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/manager.py", line 117, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/builder.py", line 135, in file_build
    return self._post_build(module, builder, encoding)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/builder.py", line 157, in _post_build
    self.delayed_assattr(delayed)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/builder.py", line 227, in delayed_assattr
    for inferred in node.expr.infer():
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/node_ng.py", line 169, in infer
    yield from self._infer(context=context, **kwargs)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/decorators.py", line 108, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/inference.py", line 289, in infer_import
    yield self.do_import_module(self.real_name(name))
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/_base_nodes.py", line 149, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 521, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/manager.py", line 160, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/manager.py", line 253, in file_from_module_name
    modname.split("."), context_file=contextfile
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/modutils.py", line 596, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/interpreter/_import/spec.py", line 393, in find_spec
    _path, modname, module_parts, processed, submodule_path or path
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/interpreter/_import/spec.py", line 355, in _find_spec_with_path
    modname, module_parts, processed, submodule_path
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/astroid/interpreter/_import/spec.py", line 204, in find_module
    submodule_path = sys.modules[modname].__path__
AttributeError: module 'importlib._bootstrap' has no attribute '__path__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/pylint/checkers/imports.py", line 502, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
  File "/home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages/pylint/checkers/imports.py", line 823, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
astroid-bug.py   1, 0 [astroid-error] astroid-bug.py: Fatal error while checking 'astroid-bug.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/me/.cache/pylint/pylint-crash-2022-08-27-06-21-55.txt'.
```

### Expected behavior

No traceback. Exact same lint runs fine on all supported versions of CPython using same version of Pylint and Astroid.
Reference: https://github.com/emcd/python-lockup/runs/8047293310?check_suite_focus=true
(Problem caught on a Github Action but also reproduced locally.)

EDIT: ~Astroid 2.12.3 ran fine on PyPy 3.8.~ Was previously using Pylint 2.14.5 which used Astroid 2.11.7, which worked on all platforms that I test.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.12.4

**Comment by DanielNoord** [comment]
The PR you are referring to can't really be the issue here: it's not included in `2.12.4` as it is targeted for `2.13.0`. This sound like another `is_namespace` issue where we assume that a namespace package has a `__path__` attribute but our recognition of namespaces packages isn't perfect.

I'll likely have some time to investigate this next week if nobody gets to it before that.

**Comment by emcd** [comment]
Yes, you are correct, @DanielNoord - sorry about that. I saw your commit sandwiched between the version bumps in Astroid and made a bad assumption. I can see now that your change was not in 2.12.4 and, indeed, no relevant commit is in that release or the previous one. Looks like the recent Pylint release bumped the Astroid requirement from 2.11 to 2.12 and so the offender is in a wider range of commits going further back in time. (Will correct the description for this bug report.) The last version of Astroid known to work for me is 2.11.7, which Pylint 2.14.5 was using.

**Comment by jacobtylerwalls** [comment]
Thanks for the report @emcd. I don't have PyPy spun up locally. Could you provide me the output of the following?

```python
>>> import importlib
>>> importlib._bootstrap.__spec__.origin
'frozen'
```

**Comment by emcd** [comment]
@jacobtylerwalls : Sure. Looks like that subattribute doesn't exist in PyPy 3.8 because the `__spec__` attribute is `None`:
```
$ python -c 'import sys, importlib; print( sys.version_info ); print( sys.pypy_version_info ); print( importlib._bootstrap.__spec__.origin )'
sys.version_info(major=3, minor=8, micro=13, releaselevel='final', serial=0)
sys.pypy_version_info(major=7, minor=3, micro=9, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'origin'
$ python -c 'import importlib; print( type( importlib._bootstrap.__spec__ ) )'
<class 'NoneType'>
```

**Comment by jacobtylerwalls** [comment]
Very helpful, @emcd! Would you be able to try out #1757 and let us know if it resolves your issue?

**Comment by emcd** [comment]
Wow - that was a quick fix!
Yes, it seems to work:
```
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/THIRD_PARTY/astroid$ git remote -v
origin  https://github.com/jacobtylerwalls/astroid.git (fetch)
origin  https://github.com/jacobtylerwalls/astroid.git (push)
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/THIRD_PARTY/astroid$ git branch
  main
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/THIRD_PARTY/astroid$ pip install . pylint==2.15.0
Processing /home/me/src/THIRD_PARTY/astroid
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pylint==2.15.0
  Using cached pylint-2.15.0-py3-none-any.whl (505 kB)
Requirement already satisfied: dill>=0.2 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (0.3.5.1)
Requirement already satisfied: platformdirs>=2.2.0 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (2.5.2)
Requirement already satisfied: isort<6,>=4.2.5 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (5.10.1)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (0.7.0)
Requirement already satisfied: tomlkit>=0.10.1 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (0.11.4)
Requirement already satisfied: typing-extensions>=3.10.0 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (4.3.0)
Requirement already satisfied: tomli>=1.1.0 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from pylint==2.15.0) (2.0.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from astroid==2.13.0.dev0) (1.7.1)
Requirement already satisfied: wrapt<2,>=1.11 in /home/me/src/python-lockup/.local/environments/pypy-3.8-7.3--linux--glibc-2.31--x86_64/lib/pypy3.8/site-packages (from astroid==2.13.0.dev0) (1.14.1)
Building wheels for collected packages: astroid
  Building wheel for astroid (pyproject.toml) ... done
  Created wheel for astroid: filename=astroid-2.13.0.dev0-py3-none-any.whl size=262428 sha256=43e1ac2b6917aadd158af5953d9f828901aa72dfaab819c0805fb0299eef1083
  Stored in directory: /tmp/pip-ephem-wheel-cache-pew8kghc/wheels/74/ef/57/67019fcf38c5abad1df8a9c4b4e7224bd2721b0744f45a56b0
Successfully built astroid
Installing collected packages: astroid, pylint
  Attempting uninstall: astroid
    Found existing installation: astroid 2.13.0.dev0
    Uninstalling astroid-2.13.0.dev0:
      Successfully uninstalled astroid-2.13.0.dev0
  Attempting uninstall: pylint
    Found existing installation: pylint 2.14.5
    Uninstalling pylint-2.14.5:
      Successfully uninstalled pylint-2.14.5
Successfully installed astroid-2.13.0.dev0 pylint-2.15.0
```
```
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/python-lockup$ pylint --version
pylint 2.15.0
astroid 2.13.0-dev0
Python 3.8.13 (4b1398fe9d76ad762155d03684c2a153d230b2ef, Mar 29 2022, 07:08:24)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/python-lockup$ cat astroid_bug.py
''' Docstring of Pylint appeasement. '''
from importlib import import_module
package = import_module( 'os' )
(pypy-3.8-7.3--linux--glibc-2.31--x86_64) ~/src/python-lockup$ pylint astroid_bug.py


Report
======
2 statements analysed.

...

Messages
--------

+-----------+------------+
|message id |occurrences |
+===========+============+




--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

Thank you.
