### ISSUE TITLE
`functools.singledispatch` being called on Context enum

### ISSUE THREAD

**Issue by ceridwen** [PyCQA/astroid#311]
```python

Traceback (most recent call last):
  File "/usr/lib/python3.4/functools.py", line 702, in dispatch
    impl = dispatch_cache[cls]
  File "/usr/lib/python3.4/weakref.py", line 352, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f95184025e8; to 'EnumMeta' at 0x1068448 (Context)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/functools.py", line 705, in dispatch
    impl = registry[cls]
KeyError: <enum 'Context'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/code/astroid/astroid/tests/unittest_zipper.py", line 56, in <module>
    print(walk_ast.example())
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/strategies.py", line 149, in example
    return self.reify(template)
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/deferred.py", line 103, in reify
    return self.wrapped_strategy.reify(value)
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/wrappers.py", line 49, in reify
    return self.wrapped_strategy.reify(value)
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/strategies.py", line 426, in reify
    return self.element_strategies[s].reify(x)
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/strategies.py", line 547, in reify
    return self.pack(self.mapped_strategy.reify(value))
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/flatmapped.py", line 47, in pack
    return morpher.become(self.expand(source))
  File "~/code/astroid/astroid/tests/unittest_zipper.py", line 52, in <lambda>
    extend = lambda path_strategy: path_strategy.flatmap(lambda path: strategies.sampled_from(possible_moves(path)).map(lambda move: path + (move,)))
  File "~/code/astroid/astroid/tests/unittest_zipper.py", line 37, in possible_moves
    node.print_tree()
  File "~/code/astroid/astroid/tree/base.py", line 480, in print_tree
    print(self.repr_tree(*args, **kws))
  File "~/code/astroid/astroid/tree/base.py", line 475, in repr_tree
    _repr_tree(self, result, set())
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 469, in _repr_node
    depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 418, in _repr_seq
    _repr_tree(child, result, done, cur_indent, depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 469, in _repr_node
    depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 418, in _repr_seq
    _repr_tree(child, result, done, cur_indent, depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 469, in _repr_node
    depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "~/code/astroid/astroid/tree/base.py", line 464, in _repr_node
    depth)
  File "~/code/astroid/astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "/usr/lib/python3.4/functools.py", line 707, in dispatch
    impl = _find_impl(cls, registry)
  File "/usr/lib/python3.4/functools.py", line 658, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "/usr/lib/python3.4/functools.py", line 646, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "/usr/lib/python3.4/functools.py", line 600, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/usr/lib/python3.4/functools.py", line 600, in <listcomp>
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/usr/lib/python3.4/functools.py", line 604, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "/usr/lib/python3.4/functools.py", line 555, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy
```

I'm not sure if this is a bug in astroid or one of its dependencies.  If it's one of the dependencies, we'll probably have to find a workaround.  This occurred while testing the zipper on context.py.

**Comment by ceridwen** [comment]
I found this bug again, this time on Python 2.7.  The characteristics are quite similar: I'm calling repr_tree() on an AST, somehow recursing through the tree finds a Context object, the Enum seems to have an inconsistent MRO, and so the whole thing crashes.

```python
Traceback (most recent call last):
  File "~/code/astroid/astroid/tests/unittest_zipper.py", line 120, in test
    @hypothesis.given(ast_strategy, strategies.integers(min_value=0, max_value=100), strategies.choices())
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 485, in wrapped_test
    print_example=True, is_final=True
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/executors.py", line 57, in default_new_style_executor
    return function(data)
  File "/usr/local/lib/python2.7/dist-packages/hypothesis/core.py", line 103, in run
    return test(*args, **kwargs)
  File "~/code/astroid/astroid/tests/unittest_zipper.py", line 123, in test
    hypothesis.note(root.repr_tree())
  File "astroid/tree/base.py", line 444, in repr_tree
    _repr_tree(self, result, set())
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 438, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 387, in _repr_seq
    _repr_tree(child, result, done, cur_indent, depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 438, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 387, in _repr_seq
    _repr_tree(child, result, done, cur_indent, depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 438, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 375, in _repr_seq
    broken = _repr_tree(node[0], result, done, cur_indent, depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 433, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 373, in _repr_seq
    broken = _repr_tree(node[0], result, done, cur_indent, depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 426, in _repr_node
    cur_indent, depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 438, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "astroid/tree/base.py", line 433, in _repr_node
    depth)
  File "astroid/util.py", line 43, in wrapper
    return old_generic_func.dispatch(type(args[0]))(*args, **kws)
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 191, in dispatch
    impl = _find_impl(cls, registry)
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 142, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 130, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 84, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 88, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "/usr/lib/python2.7/dist-packages/singledispatch.py", line 39, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy
```

I'm suspicious this may be related to https://bugs.python.org/issue23572 , in which case, we're going to have to find a workaround.

**Comment by jacobtylerwalls** [comment]
Hi :wave: and thanks for the report. Feel free to reopen if you can provide a reproducer on recent, supported versions of python and astroid. 👍
