### ISSUE TITLE
Crash when trying to infer sys.stdout

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/astroid#346]
```
from astroid import extract_node
n = extract_node('''
import sys
sys.stdout
''')
i = n.inferred()
i = i[0]
print(repr(i))
```

This will fail with
```
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    i = n.inferred()
  File "d:\projects\repos\astroid\astroid\tree\base.py", line 267, in inferred
    return list(self.infer())
  File "d:\projects\repos\astroid\astroid\decorators.py", line 86, in wrapped
    res = next(generator)
  File "d:\projects\repos\astroid\astroid\decorators.py", line 139, in raise_if_nothing_inferred
    yield next(generator)
  File "d:\projects\repos\astroid\astroid\inference.py", line 182, in infer_attribute
    for obj in owner.igetattr(self.attrname, context):
  File "d:\projects\repos\astroid\astroid\interpreter\util.py", line 41, in infer_stmts
    for inferred in stmt.infer(context=context):
  File "d:\projects\repos\astroid\astroid\context.py", line 37, in cache_generator
    for result in generator:
  File "d:\projects\repos\astroid\astroid\decorators.py", line 86, in wrapped
    res = next(generator)
  File "d:\projects\repos\astroid\astroid\interpreter\util.py", line 41, in infer_stmts
    for inferred in stmt.infer(context=context):
  File "d:\projects\repos\astroid\astroid\context.py", line 37, in cache_generator
    for result in generator:
  File "d:\projects\repos\astroid\astroid\decorators.py", line 83, in wrapped
    generator = _func(node, context, **kwargs)
  File "d:\projects\repos\astroid\astroid\inference.py", line 68, in infer_name
    frame, stmts = self.lookup(self.name)
  File "d:\projects\repos\astroid\astroid\tree\base.py", line 507, in lookup
    return self.scope().scope_lookup(self, name)
  File "d:\projects\repos\astroid\astroid\tree\scoped_nodes.py", line 224, in scope_lookup
    return self._scope_lookup(node, name, offset)
  File "d:\projects\repos\astroid\astroid\interpreter\lookup.py", line 47, in _scope_lookup
    stmts = node._filter_stmts(self.locals[name], self, offset)
  File "d:\projects\repos\astroid\astroid\tree\base.py", line 567, in _filter_stmts
    node.scope().locals)
AssertionError: (<Proxy at 0x3525350 wrapping <InterpreterObject.__stdout__ l.None at 0x3558770> at 0x3558770 with factory <function _ast_from_object.<locals>.lazy_instance at 0x03490A98>>, <Module.sys l.0 at 0xf39c70>, mappingproxy(defaultdict(<class 'list'>, {'brain_hashlib': [<Import l.None at 0x355f530>], 'zipimporter': [<ImportFrom l.None at 0x356e2f0>], 'socket': [<Import l.None at 0x355f6d0>], 'byteorder': [<AssignName.byteorder l.None at 0x3514590>], 'settrace': [<FunctionDef.settrace l.None at 0x356ed70>], 'struct': [<Import l.None at 0x355f6f0>], 'api_version': [<AssignName.api_version l.None at 0x35143d0>], 'FileFinder': [<ImportFrom l.None at 0x356e330>, <ImportFrom l.None at 0x356e310>, <ImportFrom l.None at 0x356e430>, <ImportFrom l.None at 0x356e450>, <ImportFrom l.None at 0x356e490>, <ImportFrom l.None at 0x356e4d0>, <ImportFrom l.None at 0x356e510>, <ImportFrom l.None at 0x356e550>, <ImportFrom l.None at 0x356e590>, <ImportFrom l.None at 0x356e5d0>, <ImportFrom l.None at 0x356e610>, <ImportFrom l.None at 0x356e650>, <ImportFrom l.None at 0x356e690>, <ImportFrom l.None at 0x356e6d0>, <ImportFrom l.None at 0x356e710>, <ImportFrom l.None at 0x356e750>, <ImportFrom l.None at 0x356e790>, <ImportFrom l.None at 0x356e7d0>, <ImportFrom l.None at 0x356e810>, <ImportFrom l.None at 0x356e850>, <ImportFrom l.None at 0x356e890>, <ImportFrom l.None at 0x356e8d0>, <ImportFrom l.None at 0x356e910>, <ImportFrom l.None at 0x356e950>, <ImportFrom l.None at 0x356e990>, <ImportFrom l.None at 0x356e9d0>, <ImportFrom l.None at 0x356ea10>, <ImportFrom l.None at 0x356ea50>, <ImportFrom l.None at 0x356ead0>, <ImportFrom l.None at 0x356eb10>, <ImportFrom l.None at 0x356eb50>, <ImportFrom l.None at 0x356eb90>, <ImportFrom l.None at 0x356ebd0>], 'brain_numpy': [<Import l.None at 0x35631f0>], '_hashlib': [<Import l.None at 0x355f7d0>], 'displayhook': [<FunctionDef.displayhook l.None at 0x350b970>, <AssignName.displayhook l.None at 0x3524f30>], 'dont_write_bytecode': [<AssignName.dont_write_bytecode l.None at 0x3524f70>], 'getsizeof': [<FunctionDef.getsizeof l.None at 0x3558e10>], 'base_exec_prefix': [<AssignName.base_exec_prefix l.None at 0x3514470>], 'binascii': [<Import l.None at 0x355f950>], 'path_importer_cache': [<AssignName.path_importer_cache l.None at 0x356af50>], '_functools': [<Import l.None at 0x355f9d0>], 'intern': [<FunctionDef.intern l.None at 0x355f230>], '__stdout__': [<Proxy at 0x3525350 wrapping <InterpreterObject.__stdout__ l.None at 0x3558770> at 0x3558770 with factory <function _ast_from_object.<locals>.lazy_instance at 0x03490A98>>], 'ntpath': [<Import l.None at 0x35633f0>, <Import l.None at 0x35673d0>], 'stderr': [<AssignName.stderr l.None at 0x356ec10>], 're': [<Import l.None at 0x3567f50>], 'maxunicode': [<AssignName.maxunicode l.None at 0x355f390>], '_sre': [<Import l.None at 0x355fc10>], 'operator': [<Import l.None at 0x3567d10>], 'setprofile': [<FunctionDef.setprofile l.None at 0x356ecb0>], 'sre_parse': [<Import l.None at 0x355fd10>], 'getswitchinterval': [<FunctionDef.getswitchinterval l.None at 0x3558e50>], 'brain_gi': [<Import l.None at 0x355fdd0>], '_locale': [<Import l.None at 0x355fe10>], 'brain_six': [<Import l.None at 0x355fed0>], 'tempfile': [<Import l.None at 0x355f6b0>], 'argv': [<AssignName.argv l.None at 0x35144b0>], 'random': [<Import l.None at 0x355ff90>], 'email': [<Import l.None at 0x355fa90>, <Import l.None at 0x355fb10>, <Import l.None at 0x355fb50>, <Import l.None at 0x355fd90>, <Import l.None at 0x355fe50>, <Import l.None at 0x355ffd0>, <Import l.None at 0x35630d0>, <Import l.None at 0x3563b30>, <Import l.None at 0x3567150>, <Import l.None at 0x35674d0>, <Import l.None at 0x3567650>, <Import l.None at 0x3567bd0>, <Import l.None at 0x356a370>, <Import l.None at 0x356a5b0>, <Import l.None at 0x356ae70>], '__future__': [<Import l.None at 0x3563030>], 'brain_functools': [<Import l.None at 0x35630f0>], 'six': [<Import l.None at 0x3563130>], '__interactivehook__': [<ImportFrom l.None at 0x35140d0>], 'float_repr_style': [<AssignName.float_repr_style l.None at 0x3555450>], 'stdin': [<AssignName.stdin l.None at 0x356edf0>], 'brain_threading': [<Import l.None at 0x3563230>], 'executable': [<AssignName.executable l.None at 0x3510190>], '_warnings': [<Import l.None at 0x3563270>], '_bz2': [<Import l.None at 0x356a270>], 'opcode': [<Import l.None at 0x35632b0>], 'nt': [<Import l.None at 0x35632f0>], 'reprlib': [<Import l.None at 0x3563330>], 'get_coroutine_wrapper': [<FunctionDef.get_coroutine_wrapper l.None at 0x3558c30>], 'brain_pytest': [<Import l.None at 0x35638b0>], 'genericpath': [<Import l.None at 0x356a6f0>], 'meta_path': [<AssignName.meta_path l.None at 0x355f490>], 'path_hooks': [<AssignName.path_hooks l.None at 0x356e210>], 'string': [<Import l.None at 0x35634f0>], 'brain_multiprocessing': [<Import l.None at 0x3563530>], 'FrozenImporter': [<ImportFrom l.None at 0x355f590>], 'os': [<Import l.None at 0x3567490>], '_string': [<Import l.None at 0x355f850>], 'flags': [<AssignName.flags l.None at 0x3558850>], 'getallocatedblocks': [<FunctionDef.getallocatedblocks l.None at 0x3558c50>], 'hexversion': [<AssignName.hexversion l.None at 0x3558f90>, <InterpreterObject.hexversion l.None at 0x355f1b0>], 'maxsize': [<AssignName.maxsize l.None at 0x355f290>], 'copyright': [<AssignName.copyright l.None at 0x3524e90>], '__main__': [<Import l.None at 0x35636b0>], None: [<AssignName l.None at 0x3563090>], 'posixpath': [<Import l.None at 0x356a8b0>], 'quopri': [<Import l.None at 0x3563750>], 'pprint': [<Import l.None at 0x3563c70>], 'thread_info': [<AssignName.thread_info l.None at 0x356ef10>], 'errno': [<Import l.None at 0x3567b10>], 'encodings': [<Import l.None at 0x355f890>, <Import l.None at 0x35636d0>, <Import l.None at 0x356a5f0>, <Import l.None at 0x356a730>, <Import l.None at 0x356a7f0>, <Import l.None at 0x356a8f0>, <Import l.None at 0x356ac90>], 'signal': [<Import l.None at 0x3563970>], 'getwindowsversion': [<FunctionDef.getwindowsversion l.None at 0x3558ed0>], '_debugmallocstats': [<FunctionDef._debugmallocstats l.None at 0x35141b0>], 'sre_constants': [<Import l.None at 0x3563a70>], 'ast': [<Import l.None at 0x3563ab0>], '_heapq': [<Import l.None at 0x3563af0>], '_xoptions': [<AssignName._xoptions l.None at 0x35142b0>], 'brain_builtin_inference': [<Import l.None at 0x3563b70>], 'shutil': [<Import l.None at 0x3567950>], 'keyword': [<Import l.None at 0x3563bf0>], 'pkgutil': [<Import l.None at 0x35679d0>], 'dis': [<Import l.None at 0x3563d30>], 'tarfile': [<Import l.None at 0x3563c30>], 'version': [<AssignName.version l.None at 0x356ef50>], 'TextIOWrapper': [<ImportFrom l.None at 0x3514190>, <ImportFrom l.None at 0x3514110>, <ImportFrom l.None at 0x3514170>], 'marshal': [<Import l.None at 0x3563e70>], 'threading': [<Import l.None at 0x3563ef0>], 'importlib': [<Import l.None at 0x355fbd0>, <Import l.None at 0x3563770>, <Import l.None at 0x3563bb0>, <Import l.None at 0x3567050>, <Import l.None at 0x35670d0>, <Import l.None at 0x35675d0>, <Import l.None at 0x356aab0>, <Import l.None at 0x356ad70>], 'itertools': [<Import l.None at 0x3563f30>], '_mercurial': [<AssignName._mercurial l.None at 0x3514330>], 'brain_subprocess': [<Import l.None at 0x3567850>], 'PathFinder': [<ImportFrom l.None at 0x355f5d0>], 'BuiltinImporter': [<ImportFrom l.None at 0x355f570>], 'warnings': [<Import l.None at 0x355f750>], 'wrapt': [<Import l.None at 0x355fc90>, <Import l.None at 0x35638f0>, <Import l.None at 0x3563e30>, <Import l.None at 0x3567b90>], '_weakref': [<Import l.None at 0x3567090>], '_home': [<AssignName._home l.None at 0x35141f0>], 'lzma': [<Import l.None at 0x356ae30>], 'traceback': [<Import l.None at 0x356a1b0>], 'getprofile': [<FunctionDef.getprofile l.None at 0x3558d50>], 'winreg': [<Import l.None at 0x3567190>], '_sitebuiltins': [<Import l.None at 0x355fad0>], 'stat': [<Import l.None at 0x3567210>], 'astroid': [<Import l.None at 0x355f990>, <Import l.None at 0x355ff10>, <Import l.None at 0x3563170>, <Import l.None at 0x35631b0>, <Import l.None at 0x35633b0>, <Import l.None at 0x35635b0>, <Import l.None at 0x3563690>, <Import l.None at 0x35637f0>, <Import l.None at 0x3563830>, <Import l.None at 0x3563870>, <Import l.None at 0x35639b0>, <Import l.None at 0x3563ff0>, <Import l.None at 0x3567110>, <Import l.None at 0x35671d0>, <Import l.None at 0x3567690>, <Import l.None at 0x35676d0>, <Import l.None at 0x3567750>, <Import l.None at 0x3567a50>, <Import l.None at 0x3567ad0>, <Import l.None at 0x3567d90>, <Import l.None at 0x3567f90>, <Import l.None at 0x356a430>, <Import l.None at 0x356a4f0>, <Import l.None at 0x356a870>, <Import l.None at 0x356a9b0>, <Import l.None at 0x356a9f0>, <Import l.None at 0x356aef0>, <Import l.None at 0x356af70>], 'locale': [<Import l.None at 0x3567290>], 'pyexpat': [<Import l.None at 0x355ff50>, <Import l.None at 0x3563eb0>, <Import l.None at 0x35672d0>, <Import l.None at 0x3567590>, <Import l.None at 0x356adb0>], '__stderr__': [<Proxy at 0x3525e18 wrapping <InterpreterObject.__stderr__ l.None at 0x355f310> at 0x355f310 with factory <function _ast_from_object.<locals>.lazy_instance at 0x034349C0>>], 'logilab': [<Import l.None at 0x3567350>], '_collections': [<Import l.None at 0x3567390>], 'getrecursionlimit': [<FunctionDef.getrecursionlimit l.None at 0x3558d90>], 'select': [<Import l.None at 0x356aaf0>], '_SixMetaPathImporter': [<ImportFrom l.None at 0x355f550>, <ImportFrom l.None at 0x355f5f0>], 'uu': [<Import l.None at 0x3563570>], 'path': [<AssignName.path l.None at 0x356af90>], '_random': [<Import l.None at 0x3567510>], 'imp': [<Import l.None at 0x355fa10>], 'setswitchinterval': [<FunctionDef.setswitchinterval l.None at 0x356ed30>], 'hashlib': [<Import l.None at 0x3567610>], 'datetime': [<Import l.None at 0x355fb90>], '_bootlocale': [<Import l.None at 0x3567710>], 'excepthook': [<FunctionDef.excepthook l.None at 0x350bff0>, <AssignName.excepthook l.None at 0x3510110>], 'WindowsRegistryFinder': [<ImportFrom l.None at 0x355f5b0>], 'urllib': [<Import l.None at 0x3563df0>, <Import l.None at 0x3563fb0>], 'pkg_resources': [<Import l.None at 0x355f8d0>, <Import l.None at 0x355fe90>, <Import l.None at 0x3563370>, <Import l.None at 0x3563430>, <Import l.None at 0x3563470>, <Import l.None at 0x3563610>, <Import l.None at 0x3563a30>, <Import l.None at 0x3563cb0>, <Import l.None at 0x3567790>, <Import l.None at 0x35677d0>, <Import l.None at 0x3567dd0>, <Import l.None at 0x356a070>, <Import l.None at 0x356a0b0>, <Import l.None at 0x356a1f0>, <Import l.None at 0x356a770>, <Import l.None at 0x356ac10>, <Import l.None at 0x356ad50>], 'call_tracing': [<FunctionDef.call_tracing l.None at 0x3524e30>], 'inspect': [<Import l.None at 0x3567810>], '__plen': [<AssignName.__plen l.None at 0x350bfb0>], 'platform': [<Import l.None at 0x356a0f0>, <AssignName.platform l.None at 0x356e250>], 'exc_info': [<FunctionDef.exc_info l.None at 0x3510050>], '_signal': [<Import l.None at 0x3563f70>], 'copyreg': [<Import l.None at 0x3567910>], 'builtin_module_names': [<AssignName.builtin_module_names l.None at 0x35145d0>], 'path_hook_for_FileFinder': [<ImportFrom l.None at 0x356e290>], '_compression': [<Import l.None at 0x3567990>], 'contextlib': [<Import l.None at 0x35678d0>], 'exit': [<FunctionDef.exit l.None at 0x3555550>], '_winapi': [<Import l.None at 0x35634b0>], '_getframe': [<FunctionDef._getframe l.None at 0x3514270>], 'abc': [<Import l.None at 0x3567a90>], '_thread': [<Import l.None at 0x3567b50>], 'weakref': [<Import l.None at 0x355f910>], 'warnoptions': [<AssignName.warnoptions l.None at 0x35750d0>], 'setcheckinterval': [<FunctionDef.setcheckinterval l.None at 0x356ec70>], 'functools': [<Import l.None at 0x3567c50>], 'callstats': [<FunctionDef.callstats l.None at 0x3524ed0>], 'brain_nose': [<Import l.None at 0x3567c90>], '_imp': [<Import l.None at 0x3567cd0>], 'time': [<Import l.None at 0x355fc50>], 'brain_collections': [<Import l.None at 0x3567d50>], 'is_finalizing': [<FunctionDef.is_finalizing l.None at 0x355f350>], '_struct': [<Import l.None at 0x3567a10>], '_codecs': [<Import l.None at 0x3567e10>], 'dllhandle': [<AssignName.dllhandle l.None at 0x3524ef0>], 'getfilesystemencoding': [<FunctionDef.getfilesystemencoding l.None at 0x3558d10>], 'base_prefix': [<AssignName.base_prefix l.None at 0x35144f0>], 'linecache': [<Import l.None at 0x3567e90>], 'brain_pkg_resources': [<Import l.None at 0x3567ed0>], '_weakrefset': [<Import l.None at 0x3567f10>], 'lazy_object_proxy': [<Import l.None at 0x355fa50>, <Import l.None at 0x355fd50>, <Import l.None at 0x3567410>, <Import l.None at 0x356acd0>], 'calendar': [<Import l.None at 0x3567250>], 'token': [<Import l.None at 0x3567fd0>], 'float_info': [<AssignName.float_info l.None at 0x3558a50>], '_operator': [<Import l.None at 0x3567890>], 'base64': [<Import l.None at 0x356a130>], 'zipfile': [<Import l.None at 0x356a170>], '_clear_type_cache': [<FunctionDef._clear_type_cache l.None at 0x35140f0>], 'stdout': [<AssignName.stdout l.None at 0x356ee50>], 'brain_qt': [<Import l.None at 0x356a230>], 'bz2': [<Import l.None at 0x3563d70>], 'subprocess': [<Import l.None at 0x355f810>], 'fnmatch': [<Import l.None at 0x356a2b0>], 'plistlib': [<Import l.None at 0x356a2f0>], 'VendorImporter': [<ImportFrom l.None at 0x355f4f0>], 'enum': [<Import l.None at 0x356a3b0>], '_stat': [<Import l.None at 0x356a3f0>], 'hash_info': [<AssignName.hash_info l.None at 0x3558f50>], '_ast': [<Import l.None at 0x356a330>], 'tokenize': [<Import l.None at 0x356a470>], '_socket': [<Import l.None at 0x356a4b0>], 'version_info': [<AssignName.version_info l.None at 0x3575070>], 'winver': [<AssignName.winver l.None at 0x356eef0>], 'codecs': [<Import l.None at 0x356a530>], 'exec_prefix': [<AssignName.exec_prefix l.None at 0x3510030>], 'getrefcount': [<FunctionDef.getrefcount l.None at 0x3558dd0>], 'sysconfig': [<Import l.None at 0x356a570>], 'brain_namedtuple_enum': [<Import l.None at 0x356a630>], 'msvcrt': [<Import l.None at 0x356a670>], 'sre_compile': [<Import l.None at 0x356a6b0>], '__egginsert': [<AssignName.__egginsert l.None at 0x350bdd0>], 'copy': [<Import l.None at 0x356a7b0>], 'textwrap': [<Import l.None at 0x356a830>], 'types': [<Import l.None at 0x3563db0>], '_lzma': [<Import l.None at 0x3563930>], 'zlib': [<Import l.None at 0x356a930>], '_current_frames': [<FunctionDef._current_frames l.None at 0x3514150>], 'zipimport': [<Import l.None at 0x356a970>], 'getdefaultencoding': [<FunctionDef.getdefaultencoding l.None at 0x3558cd0>], 'selectors': [<Import l.None at 0x356aa30>], '_datetime': [<Import l.None at 0x356aa70>], '__stdin__': [<Proxy at 0x35255d0 wrapping <InterpreterObject.__stdin__ l.None at 0xee4710> at 0xee4710 with factory <function _ast_from_object.<locals>.lazy_instance at 0x00D36660>>], 'set_coroutine_wrapper': [<FunctionDef.set_coroutine_wrapper l.None at 0x356ec50>], '_opcode': [<Import l.None at 0x3567450>], 'gettrace': [<FunctionDef.gettrace l.None at 0x3558e90>], 'brain_ssl': [<Import l.None at 0x356ab30>], 'int_info': [<AssignName.int_info l.None at 0x355f250>], 'heapq': [<Import l.None at 0x356ab70>], 'site': [<Import l.None at 0x356abb0>], 'distutils': [<Import l.None at 0x3563790>, <Import l.None at 0x35639f0>, <Import l.None at 0x356a050>], 'setrecursionlimit': [<FunctionDef.setrecursionlimit l.None at 0x356ecf0>], 'io': [<Import l.None at 0x355f790>, <Import l.None at 0x3567c10>], 'math': [<Import l.None at 0x356acb0>], 'getcheckinterval': [<FunctionDef.getcheckinterval l.None at 0x3558c90>], 'builtins': [<Import l.None at 0x3567310>], 'brain_mechanize': [<Import l.None at 0x3567e50>], 'xml': [<Import l.None at 0x3567550>, <Import l.None at 0x356a030>, <Import l.None at 0x356adf0>], 'modules': [<AssignName.modules l.None at 0x355f450>], 'collections': [<Import l.None at 0x355fcd0>, <Import l.None at 0x3563cf0>, <Import l.None at 0x356aeb0>], 'prefix': [<AssignName.prefix l.None at 0x356ea70>], 'brain_dateutil': [<Import l.None at 0x356af30>]})))
```

**Comment by brycepg** [comment]
I can't reproduce this on master or on Jul 14, 2016 commit

**Comment by PCManticore** [comment]
I think this reproduces in the 2.0 branch, which has a reimplementation of the raw builder. My plan is to backport the changes from that branch back to master, but we have quite a few of them so it's taking some time.

**Comment by jacobtylerwalls** [comment]
Tested in 2b30ab777278358f754c6e7e2d5f761f76274d17
