### ISSUE TITLE
Crash when trying to interpret PEP 526 variable type hints

### ISSUE THREAD

**Issue by cdunklau** [PyCQA/astroid#393]
Looks like astroid doesn't yet support PEP 526 variable type hints, new in Python 3.6

### Steps to reproduce

1. Put the code `myvar: int` in a file.
2. Run pylint against that file

### Current behavior

Pylint crashes with this traceback. Appears to point at the new node introduced in Python 3.6's AST: `AnnAssign(expr target, expr annotation, expr? value, int simple)`

```
Traceback (most recent call last):
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/pylint/lint.py", line 927, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/manager.py", line 86, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/builder.py", line 141, in file_build
    module = self._data_build(data, modname, path)
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/builder.py", line 185, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in visit_module
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/rebuilder.py", line 154, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/Users/cdunklau/Development/pngdoctor/.tox/style/lib/python3.6/site-packages/astroid/rebuilder.py", line 165, in visit
    visit_method = getattr(self, visit_name)
AttributeError: 'TreeRebuilder3k' object has no attribute 'visit_annassign'
************* Module pylint_breaks_on_AnnAssign
F:  1, 0: <class 'AttributeError'>: 'TreeRebuilder3k' object has no attribute 'visit_annassign' (astroid-error)
```

### Expected behavior

No crash, perhaps a warning about this not being supported yet?

### Pylint and Astroid Versions
- pylint 1.6.5,
- astroid 1.4.9
- Python 3.6.0 (default, Jan  9 2017, 19:38:03)

**Comment by rr-** [comment]
"I have no idea what I'm doing" kind of patch:

```diff
diff --git a/astroid/rebuilder.py b/astroid/rebuilder.py
index 4b3506b..8f90554 100644
--- a/astroid/rebuilder.py
+++ b/astroid/rebuilder.py
@@ -214,6 +214,13 @@ class TreeRebuilder(object):
                          self.visit(node.value, newnode))
         return newnode
 
+    def visit_annassign(self, node, parent):
+        """visit a AnnAssign node by returning a fresh instance of it"""
+        newnode = nodes.Assign(node.lineno, node.col_offset, parent)
+        newnode.postinit([self.visit(node.target, newnode)],
+                         self.visit(node.value, newnode))
+        return newnode
+
     def visit_assignname(self, node, parent, node_name=None):
         '''visit a node and return a AssignName node'''
         newnode = nodes.AssignName(node_name, getattr(node, 'lineno', None),
```

**Comment by rogalski** [comment]
@rr- do you mind creating a "proper" pull request? At least we can start with code review and making change ready for merge.

**Comment by rr-** [comment]
Yes sir

**Comment by PCManticore** [comment]
Thanks to @rr-, this now works in master branch.
