### ISSUE TITLE
astroid 1.5.2 Enum has no Attribute Load (Pylint 1.7.1)

### ISSUE THREAD

**Issue by Thetoxicarcade** [PyCQA/astroid#426]
### Steps to reproduce
1. update pylint.
2. run pylint on a python project
3. get traceback :/

### Current behavior
```
Traceback (most recent call last):
  File "/usr/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/lib/python2.7/site-packages/pylint/__init__.py", line 12, in run_pylint
    from pylint.lint import Run
  File "/usr/lib/python2.7/site-packages/pylint/lint.py", line 43, in <module>
    import astroid
  File "/usr/lib/python2.7/site-packages/astroid/__init__.py", line 42, in <module>
    Load = _Context.Load
AttributeError: 'Enum' object has no attribute 'Load'

```

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/astroid/__init__.py", line 42, in <module>
    Load = _Context.Load
AttributeError: 'Enum' object has no attribute 'Load'
```

**Comment by Thetoxicarcade** [comment]
Even cooler in a python3 virtualenv!

couldn't find zope, then entered into another long traceback.

AttributeError: module 'astroid.interpreter._import.spec' has no attribute 'location'

**Comment by Thetoxicarcade** [comment]
currently, removing enum and enum34 and reinstalling gets partway through, then just functools_lru_cache is missing.
