### ISSUE TITLE
RuntimeError raised while running under Python 3.7

### ISSUE THREAD

**Issue by brettcannon** [PyCQA/astroid#539]
### Steps to reproduce
1. https://github.com/Microsoft/vscode-python/blob/master/news/announce.py
2. `pylint ./announce.py`

### Current behavior
```
No config file found, using default configuration
Traceback (most recent call last):
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\decorators.py", line 104, in wrapped
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\pylint\lint.py", line 942, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\builder.py", line 153, in file_build
    return self._post_build(module, encoding)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\builder.py", line 177, in _post_build
    module = self._manager.visit_transforms(module)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\manager.py", line 62, in visit_transforms
    return self._transform.visit(node)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\transforms.py", line 83, in visit
    module.body = [self._visit(child) for child in module.body]
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\transforms.py", line 83, in <listcomp>
    module.body = [self._visit(child) for child in module.body]
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\transforms.py", line 53, in _visit
    return self._transform(node)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\transforms.py", line 35, in _transform
    if predicate is None or predicate(node):
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\brain\brain_functools.py", line 65, in _looks_like_lru_cache
    func = helpers.safe_infer(decorator.func)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\helpers.py", line 104, in safe_infer
    next(inferit)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\decorators.py", line 89, in wrapped
    res = next(generator)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\inference.py", line 238, in infer_attribute
    for owner in self.expr.infer(context):
  File "c:\users\brcan\repositories\windows\vscode-python\news\.venv\lib\site-packages\astroid\context.py", line 71, in cache_generator
    for result in generator:
RuntimeError: generator raised StopIteration
************* Module announce
F:  1, 0: <class 'RuntimeError'>: generator raised StopIteration (astroid-error)
```
### Expected behavior
No exception.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

1.6.3 (as pulled in by Pylint).

**Comment by PCManticore** [comment]
Hey @brettcannon 

Thanks for creating this issue. We don't quite support 3.7 yet, but https://github.com/PyCQA/astroid/pull/534 just landed in the master branch, which should address the error you noticed.
We have a scheduled release for the latest astroid & pylint, which will come with 3.7 support, as soon as Python 3.7 gets officially released. Also just to mention that the latest pylint & astroid version will support only 3+, while we'll have an additional branch for releasing Python 2 compatible versions (most likely pylint 1.9 and astroid 1.7)

**Comment by brettcannon** [comment]
@PCManticore thanks for the info!

**Comment by PCManticore** [comment]
That's right.

**Comment by hroncok** [comment]
Thanks for clarifying.

**Comment by PCManticore** [comment]
astroid 2.0.0.dev has been released, this should provide some support for Python 3.7.

**Comment by hooliowobbits** [comment]
One fix is if you're using a python virtualenv (or a conda environment), just specify the version of python to be 3.6.  This change can be reverted if/when the 3.7 compatibility issue is resolved.

Specifically in my case I'm using conda python, and my CI explicitly runs `conda env update -f environment.yml` every build.  So the fix for me was to explicitly mention the version of python i want, eg: `python=3.6` in my environment.yml and everything works as it had done.
