### ISSUE TITLE
Crash when handling code which stores bound method in a variable

### ISSUE THREAD

**Issue by nieltg** [PyCQA/astroid#554]
### Steps to reproduce

1. Put this code to `myfile.py`.

    ```python
    class MyClass:
        def mymethod1(self):
            pass

    i = MyClass()
    bound1 = i.mymethod1.__get__(i, MyClass)
    ```

2. Run `pylint myfile.py` to lint it.

### Current behavior

`pylint` crashes while calling a method from `astroid` module.

```
No config file found, using default configuration
************* Module linecms.b
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Missing class docstring (missing-docstring)
C:  2, 4: Missing method docstring (missing-docstring)
R:  1, 0: Too few public methods (1/2) (too-few-public-methods)
Traceback (most recent call last):
  File "/home/nieltg/.local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/checkers/base.py", line 1451, in visit_assignname
    if isinstance(utils.safe_infer(ass_type.value), astroid.ClassDef):
  File "/home/nieltg/.local/lib/python3.6/site-packages/pylint/checkers/utils.py", line 822, in safe_infer
    value = next(inferit)
  File "/home/nieltg/.local/lib/python3.6/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/nieltg/.local/lib/python3.6/site-packages/astroid/decorators.py", line 89, in wrapped
    res = next(generator)
  File "/home/nieltg/.local/lib/python3.6/site-packages/astroid/inference.py", line 172, in infer_call
    for inferred in callee.infer_call_result(self, callcontext):
  File "/home/nieltg/.local/lib/python3.6/site-packages/astroid/interpreter/objectmodel.py", line 316, in infer_call_result
    parent=cls)
TypeError: __init__() got an unexpected keyword argument 'name'
```

### Expected behavior

`pylint` doesn't crash.

### Module versions

`astroid` version:

```
1.6.5
```

`pylint` version:

```
No config file found, using default configuration
pylint 1.9.2,
astroid 1.6.5
Python 3.6.5 (default, Apr 14 2018, 13:17:30)
[GCC 7.3.1 20180406]
```

Thank you very much.

**Comment by PCManticore** [comment]
Should be fixed in the master, thanks for the report!
