### ISSUE TITLE
Cannot import 'CallFunc' in astroid 2.0 

### ISSUE THREAD

**Issue by sandjaie** [PyCQA/astroid#599]
Python version: 3.6

Facing the below issue while running `tox -e lint`. It seems to be fine if I switch to astroid==1.6.5
```
lint installed: astroid==2.0
lint runtests: commands[0] | prospector -0 -I __init__.py -I _docs/ --strictness veryhigh --max-line-length 120
Traceback (most recent call last):
  File "/tmp/workspace/component/.tox/lint/bin/prospector", line 7, in <module>
    from prospector.run import main
  File "/tmp/workspace/component/.tox/lint/lib/python3.6/site-packages/prospector/run.py", line 9, in <module>
    from prospector.config import configuration as cfg
  File "/tmp/workspace/component/.tox/lint/lib/python3.6/site-packages/prospector/config/__init__.py", line 7, in <module>
    from prospector.autodetect import autodetect_libraries
  File "/tmp/workspace/component/.tox/lint/lib/python3.6/site-packages/prospector/autodetect.py", line 4, in <module>
    from requirements_detector import find_requirements
  File "/tmp/workspace/component/.tox/lint/lib/python3.6/site-packages/requirements_detector/__init__.py", line 1, in <module>
    from requirements_detector.detect import find_requirements
  File "/tmp/workspace/component/.tox/lint/lib/python3.6/site-packages/requirements_detector/detect.py", line 5, in <module>
    from astroid import MANAGER, CallFunc, Name, Assign, Keyword, List, Tuple, Const, AssName
ImportError: cannot import name 'CallFunc'
```

**Comment by PCManticore** [comment]
`CallFunc` was deprecated and was removed in favour of `Call`. This seems to be a `requirements_detector` issue.
