### ISSUE TITLE
Unexpected error from pylint after upgrade to astroid 2.5.

### ISSUE THREAD

**Issue by drfunjohn** [PyCQA/astroid#895]
### Steps to reproduce
astroid 2.5
pylint 2.6.0
elasticsearch 7.10.1
python 3.7.3
```
from elasticsearch import Elasticsearch
es = Elasticsearch(["test"])
es.indices.delete(index="test", ignore=[400, 404])
```
1.  run pylint

### Current behavior
line 3 >>> E1123: Unexpected keyword argument 'ignore' in method call (unexpected-keyword-arg)

### Expected behavior
astroid 2.4.2: no error from pylint

**Comment by chiefnoah** [comment]
I'm seeing similar 2.5-related issues with Enum subclasses. Particularly, `Enum.__members__.items()`. Pylint complains about `__members__` have not member `items` which is incorrect.

**Comment by limburgher** [comment]
With pylint 2.6.2, and astroid 2.4.2, everything is fine. With astroid 2.5:

(note lazy_object_proxy 1.5.2 is present)

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (lazy-object-proxy 0.0.0 (/usr/lib64/python3.9/site-packages), Requirement.parse('lazy_object_proxy>=1.4.0'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pylint-3", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.6.2', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.9/site-packages/pylint/__init__.py", line 19, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/usr/lib/python3.9/site-packages/pylint/lint/__init__.py", line 75, in <module>
    from pylint.lint.check_parallel import check_parallel
  File "/usr/lib/python3.9/site-packages/pylint/lint/check_parallel.py", line 7, in <module>
    from pylint import reporters
  File "/usr/lib/python3.9/site-packages/pylint/reporters/__init__.py", line 24, in <module>
    from pylint import utils
  File "/usr/lib/python3.9/site-packages/pylint/utils/__init__.py", line 47, in <module>
    from pylint.utils.ast_walker import ASTWalker
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 6, in <module>
    from astroid import nodes
  File "/usr/lib/python3.9/site-packages/astroid/__init__.py", line 66, in <module>
    from astroid.nodes import *
  File "/usr/lib/python3.9/site-packages/astroid/nodes.py", line 23, in <module>
    from astroid.node_classes import (
  File "/usr/lib/python3.9/site-packages/astroid/node_classes.py", line 44, in <module>
    from astroid import bases
  File "/usr/lib/python3.9/site-packages/astroid/bases.py", line 36, in <module>
    MANAGER = manager.AstroidManager()
  File "/usr/lib/python3.9/site-packages/astroid/util.py", line 27, in <lambda>
    lambda: importlib.import_module("." + module_name, "astroid")
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/astroid/manager.py", line 29, in <module>
    from astroid.interpreter._import import spec
  File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 29, in <module>
    from . import util
  File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/util.py", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 597, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lazy_object_proxy>=1.4.0' distribution was not found and is required by astroid

**Comment by hippo91** [comment]
@drfunjohn thanks for your report.
@chiefnoah and @limburgher can you open separate issues with a clear reproducer?
Thanks in advance

**Comment by limburgher** [comment]
Done, thanks! https://github.com/PyCQA/astroid/issues/897

**Comment by hippo91** [comment]
@drfunjohn i identified the faulty commit. I am looking for a patch.

**Comment by drfunjohn** [comment]
Wow, thanks for quick response.

**Comment by hippo91** [comment]
You are welcome but the patch seems tricky...

**Comment by hippo91** [comment]
@drfunjohn  i reverted the faulty commit in #901. I am the author of this commit. It was a try to improve the inference of `numpy` objects.
Apologies for the regression you faced.
