### ISSUE TITLE
astroid unable to find lazy_object_proxy with pylint 2.6.2, astroid 2.5

### ISSUE THREAD

**Issue by limburgher** [PyCQA/astroid#897]
With pylint 2.6.2, and astroid 2.4.2, everything is fine. With astroid 2.5:

(note lazy_object_proxy 1.5.2 is present)

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 582, in _build_master
ws.require(requires)
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 899, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 790, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (lazy-object-proxy 0.0.0 (/usr/lib64/python3.9/site-packages), Requirement.parse('lazy_object_proxy>=1.4.0'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/pylint-3", line 33, in
sys.exit(load_entry_point('pylint==2.6.2', 'console_scripts', 'pylint')())
File "/usr/lib/python3.9/site-packages/pylint/init.py", line 19, in run_pylint
from pylint.lint import Run as PylintRun
File "/usr/lib/python3.9/site-packages/pylint/lint/init.py", line 75, in
from pylint.lint.check_parallel import check_parallel
File "/usr/lib/python3.9/site-packages/pylint/lint/check_parallel.py", line 7, in
from pylint import reporters
File "/usr/lib/python3.9/site-packages/pylint/reporters/init.py", line 24, in
from pylint import utils
File "/usr/lib/python3.9/site-packages/pylint/utils/init.py", line 47, in
from pylint.utils.ast_walker import ASTWalker
File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 6, in
from astroid import nodes
File "/usr/lib/python3.9/site-packages/astroid/init.py", line 66, in
from astroid.nodes import *
File "/usr/lib/python3.9/site-packages/astroid/nodes.py", line 23, in
from astroid.node_classes import (
File "/usr/lib/python3.9/site-packages/astroid/node_classes.py", line 44, in
from astroid import bases
File "/usr/lib/python3.9/site-packages/astroid/bases.py", line 36, in
MANAGER = manager.AstroidManager()
File "/usr/lib/python3.9/site-packages/astroid/util.py", line 27, in
lambda: importlib.import_module("." + module_name, "astroid")
File "/usr/lib64/python3.9/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/usr/lib/python3.9/site-packages/astroid/manager.py", line 29, in
from astroid.interpreter._import import spec
File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/spec.py", line 29, in
from . import util
File "/usr/lib/python3.9/site-packages/astroid/interpreter/_import/util.py", line 4, in
import pkg_resources
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 3257, in
def _initialize_master_working_set():
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 3240, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 3269, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 584, in _build_master
return cls._build_from_requirements(requires)
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 597, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "/usr/lib/python3.9/site-packages/pkg_resources/init.py", line 785, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lazy_object_proxy>=1.4.0' distribution was not found and is required by astroid

**Comment by hippo91** [comment]
@limburgher what is the code you are linting?

**Comment by limburgher** [comment]
Any Python 3 code. Smallest file I've tried is:

`#!/usr/bin/python3

print("Hello, world!)
`

**Comment by hippo91** [comment]
@limburgher thanks! 
Smaller snippet would be hard to find! :smile:

**Comment by hippo91** [comment]
@limburgher i'm sorry but i'm totally unable to reproduce it.
I tested it with a virtual environment and its runs normally.
```
pip freeze
astroid==2.5
isort==5.7.0
lazy-object-proxy==1.5.2
mccabe==0.6.1
-e git+https://github.com/hippo91/pylint.git@6e1cca143f2e0c6f20643573bfddb53ec02e66b4#egg=pylint
toml==0.10.2
wrapt==1.12.1
```

**Comment by limburgher** [comment]
Interestingly, pip freeze gives me the same for those modules except:

lazy-object-proxy==0.0.0

This let to finding a packaging bug in Fedora's python-lzay-object-proxy package. I spoke with the maintainer.

Since she's me, I'm confident she'll get the fix out quickly. 

Sorry for the noise. :)

**Comment by hippo91** [comment]
No problem @limburgher!
Thanks for your work on Fedora.
